### ISSUE TITLE
[Front] Page: Edit Research -> Block: Schedule

### ISSUE THREAD

**Issue by stepushchenko** [MindCollectorCompany/front#15]
В рамках данной задачи требуется реализовать **функциональность управления периодами исследования**. 

Кнопка Add period, при нажатии на которую открывается модальное окно с полями (Start date, Finish Date, кнопка Add). При нажатии на кнопку Add период появляется в таблице с периодами. 

Периоды в виде таблицы: 
- Start date
- Finish date
- Button: Edit
 
При нажатии на кнопку Edit открывается модальное окно, в котором можно отредактировать дату начала и конца периода и нажать кнопку Save. 

**Модальное окно создания периода** 
Title: Add period
Form:
- Date input: Start date
- Date input: Finish date
- Button: Add 

При нажатии на кнопку Add модальное окно закрывается, период сохраняется, созданный период появляется в списке периодов. 

![Image](https://github.com/MindCollectorCompany/front/assets/46559692/9b6232ee-6d7f-4bdc-86de-083bbcc79ac6)

![Image](https://github.com/MindCollectorCompany/front/assets/46559692/f8e46cac-5fbc-4c5c-a24d-b7456e8fdba3)

**Comment by lex13s** [comment]
pages -> results
