### ISSUE TITLE
[Front] Logo and favicon

### ISSUE THREAD

**Issue by stepushchenko** [MindCollectorCompany/front#17]
1. Add a logo to the header
2. Add a favicon

Logo:
![Image](https://github.com/MindCollectorCompany/front/assets/46559692/cfcf7591-d816-4158-859f-7c38c595651d)
Favicon: 
![Image](https://github.com/MindCollectorCompany/front/assets/46559692/f5cde7a7-7b97-4a75-bb8a-b80e7d229587)

**Comment by Mirmidon** [comment]
исправлено кроме компонентов material (input. button, etc)

**Comment by stepushchenko** [comment]
Давай сразу цвета кнопок приведем к следующему виду: 
Main button - Primary color
Edit - Light color
Recharge - Success color

**Comment by stepushchenko** [comment]
Фавикон пока не вижу на сайте и в коде его тоже нет.
