### ISSUE TITLE
[Front] Menu with correct structure

### ISSUE THREAD

**Issue by stepushchenko** [MindCollectorCompany/front#2]
Верхнее меню для авторизованного пользователя: 
![Image](https://github.com/MindCollectorCompany/front/assets/46559692/120b6c8a-3dcc-4663-84f5-0b08afbd037d)

- [x] логотип, при нажатии открывается mindcollector.io 
- [x] Projects, при нажатии открывается страница Projects
- [x] [прижать к правому краю] Account, при нажатии откроется страница Account
- [x] [прижать к правому краю] Log out, при нажатии пользовать теряет авторизацию и перенаправляется на mindcollector.io

**Comment by Mirmidon** [comment]
во втором варианте где список проджектов будет??

**Comment by stepushchenko** [comment]
На странице Projects.
