### ISSUE TITLE
[Front] Bugs-redesign

### ISSUE THREAD

**Issue by stepushchenko** [MindCollectorCompany/front#23]
На страницах Sign in и Sign up: 
- открыть возможность для использования почты со знаком плюс (ilia.stepushchenko+1@gmail.com)

На старнице Projects: 
- убери, пожалуйста, кнопку Edit в каждом проекте, она останется только на странице конкретного проекта
- кнопку recharge сделай, пожалуйста, в той же колонке, что и сам баланс (то есть просто через пробел от беланса) и не в виде кнопки, а в виде ссылки

На странице Project: 
- добавить кнопку Edit (ту самую, которую мы убираем из каждой строчки на странице Projects) сразу после кнопки Create research и сделать кнопку Edit серым цветом, чтобы она была вторичной

Рефреш: 
- время от времени неожиданно разлогиневает с ошибкой как на сриншоте

![Image](https://user-images.githubusercontent.com/46559692/260209326-144c436c-354d-4efe-b92b-b7c2ad0e0ee1.png)

**Comment by lex13s** [comment]
@stepushchenko 
На рефреш нужен отдельный баг - ни разу не ловил эту ошибку/ ЕЕ суть - якобы клиент токен не отправил при рефреше, что очень странно
